# Ansible Inventory — Auto-generated by Terraform
# Do NOT edit manually. Re-run 'terraform apply' to regenerate.

[all:vars]
ansible_ssh_private_key_file=${ssh_key_path}
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false

[servers]
%{ for name, inst in insti ~}
${name} ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}
