- name: Configure Agent
  hosts: jenkins-agent
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Refresh SSH connection to apply group changes
      meta: reset_connection

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install conntrack 
      apt:
        name:
          - conntrack
        state: present

    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /tmp/minikube-linux-amd64
        mode: '0755'

    - name: Install Minikube to /usr/local/bin
      copy:
        src: /tmp/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
        remote_src: yes

    - name: Download Kubectl binary
      get_url:
        url: https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Start Minikube
      become: no
      shell: minikube start --force --driver=docker
      register: minikube_start
      changed_when: "'Done!' in minikube_start.stdout"

    - name: Wait for Minikube to be ready
      pause:
        seconds: 45

    - name: Download Helm installer script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm installer
      shell: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Add Prometheus community Helm repo
      become: no
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Add Grafana Helm repo
      become: no
      shell: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Update Helm repositories
      become: no
      shell: helm repo update

    - name: Create Monitoring Namespace
      become: no
      shell: kubectl create namespace monitoring
      ignore_errors: yes

    - name: Install Prometheus
      become: no
      shell: helm install prometheus prometheus-community/prometheus --namespace monitoring

    - name: Install Grafana
      become: no
      shell: helm install grafana grafana/grafana --namespace monitoring

    - name: Expose Prometheus Service
      become: no
      shell: kubectl expose service prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-ext --namespace monitoring
      ignore_errors: yes

    - name: Expose Grafana Service
      become: no
      shell: kubectl expose service grafana --type=NodePort --target-port=3000 --name=grafana-ext --namespace monitoring
      ignore_errors: yes